// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // { type: "autogenerated", dirName: "01-cours" }
    {
      type: "doc",
      label: "1 - Intro 🏠",
      id: "cours/rencontre1",
    },
    {
      type: "doc",
      label: "2 - Variables",
      id: "cours/rencontre2",
    },
    {
      type: "doc",
      label: "3 - Structures de contrôle 🎚",
      id: "cours/rencontre3",
    },
    {
      type: "doc",
      label: "4 - Fonctions",
      id: "cours/rencontre4",
    },
    {
      type: "doc",
      label: "5 - Algorithmique 🧮 et débogage 🐞",
      id: "cours/rencontre5",
    },
    {
      type: "doc",
      label: "6 - Intégration 🔨",
      id: "cours/rencontre6",
    },
    {
      type: "doc",
      label: "7 - Examen intra 🧪",
      id: "cours/rencontre7",
    },
    {
      type: "doc",
      label: "8 - Fichiers 🗂",
      id: "cours/rencontre8",
    },
    {
      type: "doc",
      label: "9 - Numpy",
      id: "cours/rencontre9",
    },
    {
      type: "doc",
      label: "10 - Graphiques 📈",
      id: "cours/rencontre10",
    },
    {
      type: "doc",
      label: "11 - Algorithmique 🧮 (2)",
      id: "cours/rencontre11",
    },
    {
      type: "doc",
      label: "12 - Classes et objets",
      id: "cours/rencontre12",
    },
    {
      type: "doc",
      label: "13 - Intégration 🔨",
      id: "cours/rencontre13",
    },
    {
      type: "doc",
      label: "14 - Réseaux de neurones 🧠",
      id: "cours/rencontre14",
    },
    {
      type: "doc",
      label: "15 - Examen final 🧪",
      id: "cours/rencontre15",
    }
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
  recettes: [{ type: "autogenerated", dirName: "03-recettes" }],
};

module.exports = sidebars;
