// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // { type: "autogenerated", dirName: "01-cours" }
    {
      type: "doc",
      label: "1 - 🏠 Intro",
      id: "cours/rencontre1",
    },
    {
      type: "doc",
      label: "2 - 🧮 Variables et opérateurs",
      id: "cours/rencontre2",
    },
    {
      type: "doc",
      label: "3 - ⚙️ Fonctions",
      id: "cours/rencontre3",
    },
    {
      type: "doc",
      label: "4 - 🔍 Expressions booléennes",
      id: "cours/rencontre4",
    },
    {
      type: "doc",
      label: "5 - 🔄 Boucles",
      id: "cours/rencontre5",
    },
    {
      type: "doc",
      label: "6 - 📥 TP1 - Remise (20%)",
      id: "cours/rencontre6",
      className: "tp",
    },
    {
      type: "doc",
      label: "7 - 📝 Examen intra formatif",
      id: "cours/rencontre7",
    },
    {
      type: "doc",
      label: "8 - 📝 Examen intra (20%)",
      id: "cours/rencontre8",
      className: "examen",
    },
    {
      type: "doc",
      label: "9 - 🔡 String, List et Dict",
      id: "cours/rencontre9",
    },
    {
      type: "doc",
      label: "10 - 🗂 Fichiers",
      id: "cours/rencontre10",
    },
    {
      type: "doc",
      label: "11 - 🐼 Numpy et Pandas",
      id: "cours/rencontre11",
    },
    {
      type: "doc",
      label: "12 - 🤖 Graphiques, Scikit-learn",
      id: "cours/rencontre12",
    },
    {
      type: "doc",
      label: "13 - 🛠️TP2",
      id: "cours/rencontre13",
    },
    {
      type: "doc",
      label: "14 - 📥 TP2 - Remise (30%)",
      id: "cours/rencontre14",
      className: "tp",
    },
    {
      type: "doc",
      label: "15 - 📝 Examen final (30%)",
      id: "cours/rencontre15",
      className: "examen",
    }
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
  recettes: [{ type: "autogenerated", dirName: "03-recettes" }],
  aidememoire: [{ type: "autogenerated", dirName: "04-aidememoire" }],
};

module.exports = sidebars;
