// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // { type: "autogenerated", dirName: "01-cours" }
    {
      type: "doc",
      label: "1 - 🏠 Intro",
      id: "cours/rencontre1",
    },
    {
      type: "doc",
      label: "2 - 🧮 Variables et fonctions",
      id: "cours/rencontre2",
    },
    {
      type: "doc",
      label: "3 - ⚙️ Création de fonctions",
      id: "cours/rencontre3",
    },
    {
      type: "doc",
      label: "4 - 🔍 Expressions booléennes",
      id: "cours/rencontre4",
    },
    {
      type: "doc",
      label: "5 - 🔄 Boucles",
      id: "cours/rencontre5",
    },
    {
      type: "doc",
      label: "6 - 🧩 Struct. combinées, TP1",
      id: "cours/rencontre6",
    },
    {
      type: "doc",
      label: "7 - Formatif / Remise TP1 (20%)",
      id: "cours/rencontre7",
      className: "tp",
    },
    {
      type: "doc",
      label: "8 - 📝 Examen intra (20%)",
      id: "cours/rencontre8",
      className: "examen",
    },
    {
      type: "doc",
      label: "9 - 📦 List, Set, Tuple, Dict",
      id: "cours/rencontre9",
    },
    {
      type: "doc",
      label: "10 - 🗂 Fichiers, Listes 2D, 3D...",
      id: "cours/rencontre10",
    },
    {
      type: "doc",
      label: "11 - 🔢 Numpy",
      id: "cours/rencontre11",
    },
    {
      type: "doc",
      label: "12 - 🤖 IA, Graphiques",
      id: "cours/rencontre12",
    },
    {
      type: "doc",
      label: "13 - 🛠️ TP2",
      id: "cours/rencontre13",
    },
    {
      type: "doc",
      label: "14 - Formatif / Remise TP2 (30%)",
      id: "cours/rencontre14",
      className: "tp",
    },
    {
      type: "doc",
      label: "15 - 📝 Examen final (30%)",
      id: "cours/rencontre15",
      className: "examen",
    }
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
  recettes: [{ type: "autogenerated", dirName: "03-recettes" }],
  aidememoire: [{ type: "autogenerated", dirName: "04-aidememoire" }],
};

module.exports = sidebars;
